// Re-export from config for backward compatibility
export {
  EXPENSE_CATEGORIES as CATEGORIES,
  CHART_COLORS,
  MONTHS,
} from '../config/constants';

import { Expense } from '../types';

export const SAMPLE_EXPENSES: readonly Expense[] = [
  {
    id: 1,
    merchant: "Weekly Groceries",
    currency: "USD",
    amount: 125.5,
    category: "Groceries",
    location: "Supermarket",
    createdAt: "2025-10-03T10:00:00Z",
  },
  {
    id: 2,
    merchant: "Electricity Bill",
    currency: "USD",
    amount: 75.2,
    category: "Utilities",
    location: "Home",
    createdAt: "2025-10-05T11:30:00Z",
  },
  {
    id: 3,
    merchant: "Gas Station",
    currency: "USD",
    amount: 50.0,
    category: "Transportation",
    location: "Shell",
    createdAt: "2025-10-05T17:45:00Z",
  },
  {
    id: 4,
    merchant: "Cinemark",
    currency: "USD",
    amount: 32.0,
    category: "Entertainment",
    location: "Movie Theater",
    createdAt: "2025-10-07T20:15:00Z",
  },
  {
    id: 5,
    merchant: "Restaurant",
    currency: "USD",
    amount: 88.75,
    category: "Food & Dining",
    location: "Downtown",
    createdAt: "2025-10-08T19:00:00Z",
  },
  {
    id: 6,
    merchant: "Clothing Store",
    currency: "USD",
    amount: 150.0,
    category: "Shopping",
    location: "Mall",
    createdAt: "2025-10-10T14:20:00Z",
  },
  {
    id: 7,
    merchant: "Pharmacy",
    currency: "USD",
    amount: 22.4,
    category: "Healthcare",
    location: "CVS",
    createdAt: "2025-10-12T09:05:00Z",
  },
  {
    id: 8,
    merchant: "Fresh Market",
    currency: "USD",
    amount: 65.3,
    category: "Groceries",
    location: "Grocery Store",
    createdAt: "2025-10-12T15:00:00Z",
  },
  {
    id: 9,
    merchant: "Transit Authority",
    currency: "USD",
    amount: 60.0,
    category: "Transportation",
    location: "Bus Station",
    createdAt: "2025-10-01T08:00:00Z",
  },
  {
    id: 10,
    merchant: "Netflix",
    currency: "USD",
    amount: 15.99,
    category: "Entertainment",
    location: "Online",
    createdAt: "2025-10-15T12:00:00Z",
  },
  {
    id: 11,
    merchant: "Café",
    currency: "USD",
    amount: 18.5,
    category: "Food & Dining",
    location: "Downtown",
    createdAt: "2025-10-16T13:10:00Z",
  },
  {
    id: 12,
    merchant: "Coffee Shop",
    currency: "USD",
    amount: 25.0,
    category: "Food & Dining",
    location: "Local Store",
    createdAt: "2025-10-18T16:00:00Z",
  },
  {
    id: 13,
    merchant: "Internet Provider",
    currency: "USD",
    amount: 65.0,
    category: "Utilities",
    location: "Home",
    createdAt: "2025-09-28T10:00:00Z",
  },
] as const;